config/routes.rb
require 'resque/server'
require 'resque_scheduler'
require 'subdomain'
Resque::Scheduler.dynamic = true
Apptual::Application.routes.draw do

  get "programs/:id/search" => "search#index", :as => :index_search

  devise_for :users, :controllers => {:registrations => 
    "registrations", :invitations => 'invitations', :omniauth_callbacks => "users/omniauth_callbacks",
     :passwords => "passwords", :confirmations => 'confirmations'
  } do
      get  "/users/invitation/accept" => "invitations#accept"
      get  "/users/invitation/check_email" => "invitations#check_email"
      get  "/users/invitation/find_user" => "invitations#find_user"
      get  "/users/invitation/invite_existing" => "invitations#invite_existing"
  end
  
  devise_scope :user do
    get "/users/sign_up/step_2/:id" => "registrations#step_2", 
      :as => :step_2_user_registration
    get "/users/force/:id" => "registrations#force_sign_in", :as => :force_sign_in
    put "users/update_without_session/:id" => "registrations#update_without_session",
      :as => :update_without_session_registration
    get "/users/about_me" => "registrations#about_me", :as => :about_me_registration
    put "/users/update_about_me" => "registrations#update_about_me", :as => :update_about_me_registration
    put "/users/accept_invitation" => "registrations#accept_invitation", :as => :invitation_validation
    get "/profile/:id" => "registrations#show", :as => :user

    post 'users/omniauth_callbacks/create_twitter_user' => "users/omniauth_callbacks#create_twitter_user"
    get "/users/finish" => "registrations#finish", :as => :finish_registration
    get "users/show_faq" => "registrations#show_faq"
    get "users/pages_visited" => "registrations#pages_visited"
    put "/users/social_update" => "registrations#social_update", :as => :social_update
    get "/users/edit_user" => "registrations#edit_user", :as => :edit_user
    put "users/admin_update/:id" => "registrations#admin_update", :as => :admin_update
  end
  resources :organisations do
    get "/members/:role_code" => "organisations#members", :on => :member,
      :as => :members
    get   :eco_login,      on: :member
    get   :buzz,      on: :member
    post  :buzz_post, on: :member
    get   :popup_details,      on: :member
    resources :community_feeds, :only => [:destroy] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
    end
    resource :summary, :controller => :eco_summaries
    get :faqs,      on: :member    
    put :faq_save,      on: :member
    put :faq_update,      on: :member
    delete :faq_destroy,      on: :member
    post :contact_us, :on => :member
    resources :coupons, :only => [:index, :show, :create, :new, :destroy]
    resources :subscriptions, :only => [:edit, :create, :new, :update, :delete] do
      get   :soft_deleted_user,   on: :collection
    end
    
    get   :reactivate_account,  on: :collection
    get   :deactivate_account,  on: :collection

    get :badge_authority_details
    post :badge_authority_details_save
    
  end

  resources :comments, :only => [:create, :destroy] do
    put :like, :on => :member
    put :unlike, :on => :member
    get :like_from_mail, :on => :member
  end

  resources :surveys do
    resources :questions
  end

  resources :payments do
    get :plans, on: :collection
    get :subscriptions, on: :collection
    get :check_vat, on: :collection
    get :refund, on: :collection    
  end

  resources :ecosystems, :only => [:index, :show, :create, :new, :destroy]

  resources :user_contact_requests, :only => [:create]

  resources :programs do
    get "manage_form"
    put "manage_form_save"
    put "feed_form"
    get "change_feed_form"
    get :dashboard
    get :export_users_detail
    get :export_projects_detail
    get :download_phase_in_csv, :on => :member
    get :get_action_list
    get :community_tab
    put :update_custom_filter
    get :get_rule
    put :update_rule
    delete :delete_rule
    collection do
      post :contact_us
    end

    resources :voting_sheets, :only => :none do
      post :download,:on=>:collection
    end

    resources :messages, :only => :none do
      put :participants, :on => :collection
      put :pitches, :on => :collection
      put :mentor_pitches, :on => :collection
      put :phase_messages, :on => :collection
      put :msg_pitch_team, :on => :collection
      get :customize_email_messages, :on => :collection
      get :feedback_emails,:on=>:collection
      post :feedback_emails_save,:on=>:collection
      get :admin_invite ,:on=>:collection
      post :admin_invite_save ,:on => :collection
      get :team_member_invite ,:on=>:collection
      post :team_member_invite_save ,:on => :collection
      get :team_mentor_invite ,:on=>:collection
      post :team_mentor_invite_save ,:on => :collection
      get :comment_emails,:on=>:collection
      post :comment_emails_save,:on=>:collection
      get :mentor_offer_invite,:on=>:collection
      post :mentor_offer_invite_save,:on=>:collection
      get :join_team,:on=>:collection
      post :join_team_save,:on=>:collection
      get :submit_pitch,:on=>:collection
      post :submit_pitch_save,:on=>:collection
      get :collaboration_successfull,:on=>:collection
      post :collaboration_successfull_save,:on=>:collection
      get :download_csv,:on=>:collection
      get :join_team_email,:on=>:collection
      post :join_team_email_save,:on=>:collection
      get :declines_join_team_request,:on=>:collection
      post :declines_join_team_request_save,:on=>:collection
      get :rate_events_mail,:on=>:collection
      post :rate_events_mail_save,:on=>:collection
    end

    resources :customisations, :only => [:new, :create] do
      delete :delete_custom_fields, :on => :collection
      put :remove_basic_fields, on: :collection
    end

    resources :faqs, :only => [:new, :create, :show, :update, :destroy]
    resources :settings, :only => [:new, :create] do
      post :cloneable, on: :collection
    end

    resources :workflows, :only => [:index, :create] do
      put :toggle_status, on: :member
      put :achieved, on: :member
      put :undo, on: :member
      delete :delete_milestone, on: :member
    end

    resources :events do
      get :accept, :on => :member
      post :reject_participant, :on => :collection
      get :manage_participant, :on => :member
      get :confirm_participant, :on => :collection
      resources :event_sessions, :only => [:destroy] do
        get :export_event_session, :on => :member
        get :print_event_session, :on => :member
        post :message_all, :on => :collection
      end
    end

    resources :community_feeds, :only => [:index, :create, :destroy, :show] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
      put :non_sticky, :on => :member
      put :sticky, :on => :member
      put :remove_from_blog, :on => :member
      put :add_to_blog, :on => :member
      put :remove_from_eco_blog, :on => :member
      put :add_to_eco_blog, :on => :member
      get :like_from_mail, :on => :member
    end
    resource :summary, :controller => :program_summaries do
      get :authorize_eventbrite_account, :on => :member
      get :create_eventbrite_account, :on => :member
      put :add_eventbrite_user_key, :on => :member
      get :fetch_eventbrite_events, :on => :member
      post :create_eventbrite_events, :on => :member
      put :generate_nav_links, :on => :collection
    end
    resource :program_plans do
      get :attending, :on => :member
      get :not_attending, :on => :member
      get :attendees, :on => :member
    end
    resource :scope, :controller => :program_scopes
    resource :invitation, :controller => :program_invitations do
      get :invites, :on => :collection
      post :send_invites, :on => :collection
    end
    
    resource :due_diligence do
      get :judging_score, :on => :collection
      get :export_judging_details, :on => :collection
    end
    
    resources :phases, :only => :index do
      put :task_manager, :on => :collection
      post :task_manager, :on => :collection
      post :remind, :on => :collection
      post :message_all, :on => :collection
      get :manage, :on => :collection
      put :transition, :on => :collection
    end
    resources :pitches do
      post :iteration, :on => :member
      get :feeds, :on => :member
      get :team, :on => :member
      get :nudge, :on => :member
      get :be_mentor, :on => :member
      put :be_member, :on => :member
      get :join_team, :on => :member
      put :join_team, :on => :member
      put :invite_mentor, :on => :member
      get :contacts, :on => :member
      put :add_mentor, :on => :member
      put :remove_mentor, :on => :member
      put :add_membership_requester, :on => :member
      put :remove_membership_requester, :on => :member
      put :add_collaborater_requester, :on => :member
      put :remove_collaborater_requester, :on => :member
      put :shortlist, :on => :member
      put :finalist, :on => :member
      put :skills_needed, :on => :member
      post :due_diligence, :on => :member
      get :recommended_events, :on => :member
      put :assign_mentor, :on => :member
      delete :gallery_pic_remove, :on => :member
      
      resources :edit_pitch_field, :only => :none do
        get :toggle_edit_status, :on => :collection
      end
      
      resources :pitch_privacies, :only => [] do
        get :change_privacy_of_pitch, :on => :collection
      end
      
      resources :pitch_work_flow, :only => [] do
        get :check_required_fields, :on => :collection
      end
      
      get '/courses/:course_id/show' => "courses#show", as: :course_show
      post :refer_pitch_some_one, :on => :member
      post :be_collaborater, :on => :member
      resources :documents, :only => [:index, :create, :destroy] do

app/models/faq.rb
class Faq

  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :organisation
  belongs_to :program
  
  field :question,:type => String
  field :answer,  :type => String 
  mount_uploader :attachment, AttachmentUploader
  field :link,   :type => String
  field :tags,   :type => Array 

  field :role_code, :type => String
  field :relevant_page, :type => String, :default => "summary_page"
  scope :have_tags, lambda{|tag| where(:tags.in => [tag])}
  #validates :question, :answer, :presence => true


end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  before_filter :load_program

  def new
    @faq = @program.faqs.new
    if params[:role].present?
      @faqs = @program.faqs.where(role_code: params[:role])
    else
      @faqs = @program.faqs.all.asc(:created_at)
    end
  end

  def create
    @program = @program.update_attributes(params[:program][:faqs_attributes])
    if @program.save
      redirect_to  edit_program_path(@program)
    else
      redirect_to "/programs/#{@program.id}/faqs/new"
    end
  end



  def update
    @faq = Faq.find(params[:id])

    if @faq.update_attributes(params[:faq])
      redirect_to :back
    else
      render :action=> :new
    end
  end

  def destroy
    if params[:id].present?
      faq = Faq.where(id: params[:id]).first
      if faq.destroy
        redirect_to "/programs/#{@program.id}/faqs/new"
      else
        redirect_to "/programs/#{@program.id}/faqs/new"
      end
    end
  end


  def show
    @faqs = @program.faqs.all
  end


  private

  def load_program
    @program = Program.find(params[:program_id])
  end

end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_ecosystem_form.html.erb
<style type="text/css">
  .clr {
    clear: both;
}
.add_new_faq{float:left;}
.upload {
border:0px solid #000000;
}

</style>
<div class="row">
  <div class="col-sm-12">
    <div role="alert" class="alert alert-info">
      <p><b>Create your FAQ section here</b></p>
      <br />
      <p>Add a list of questions and answers that your users will find helpful. This will appear when users clicks on the FAQ section through out the site </p>
    </div>
  </div>
</div>
<br />
<%= f.fields_for :faqs , @organisation.faqs.build do |faq | %>
  <div style="margin-bottom: 10px;"><%= faq.text_field :question , :class => "autogrow form-control", :placeholder => "Type your question here" %></div>
  <div style="margin-bottom: 0;" class="new-status-box"><%= faq.text_area :answer ,:placeholder => "Type your answer to the question here" %></div>

  <div class="link_box" style="margin-top:8px;">
    <span class="img_link_lbl">Image Link:</span>
    <span class="vid_link_lbl">Youtube / Vimeo Link:</span>
    <span class="l_link_lbl">Link or File:</span>
    <span class="gallery_link_lbl">Pictures:</span>
    <span class="l_link_lbl vid_link_lbl img_link_lbl gallery_link_lbl">
      <%= faq.text_field :link, :class => "file_url form-control" %>
    </span>
    <span class="l_link_lbl img_link_lbl gallery_link_lbl upload">
    OR <%= faq.file_field :attachment %>
    </span>
  </div>
<div class="box-content-bottom">
  <%= link_to image_tag("ico-image.png"), "#", :class => "addImage", :name => "img_link_lbl" %>
  <%= link_to image_tag("ico-video.png"), "#", :class => "addImage", :name => "vid_link_lbl" %>
  <%= link_to image_tag("ico-link.png"), "#", :class => "addImage", :name => "l_link_lbl" %>
  <%= link_to image_tag("ico-gallery.png"), "#", :class => "addImage", :name => "gallery_link_lbl" %>

  <a href="#" class="showNewTagCont" style="margin-top:10px;"><img src="/images/ico-tag.png" alt="Ico-tag"></a>

  <div style="margin-left: 10px; display:inline;">
    <span class="newTag" style="display:none">
    <%= faq.text_field :tags, class: "newtag newTagVal", placeholder: "+ add tag", style: "margin-left: 10px; width: 100px;margin_top:0px;" %>
    </span>
  </div>

  <% relevant_pages = %w(eco_summary_page) %>
  <span class= "pull-right"> <%= faq.collection_select :relevant_page, relevant_pages, :to_s, :titleize, {:include_blank => 'Tag to', :selected => 'eco_summary_page'}, :class=>"form-control", :style=>"margin-right:0;" %> </span>
	<div class="clear"></div>
</div>
<% end %>

<div class="clr"></div>
<div>
  <%#= f.link_to_add "+ ADD NEW QUESTION", :faqs , :class=>"add_new_faq clr"%>
  <div class="clr"></div>
  <div class="pull-right"><%= f.submit "Save", :id => "submit" %></div>
</div>



<script type="text/javascript">
  jQuery('#main').on('change', '.tag_applicant', function(){
  var tag_applicant = $('.tag_applicant').val();
  if(tag_applicant != '')
  $('.newtag').val(tag_applicant);
  });
  bkLib.onDomLoaded(function() {
    new nicEditor().panelInstance('organisation_faqs_attributes_0_answer');
  });
</script>

app/views/faqs/_edit.html.erb
<style type="text/css">
  .clr {
    clear: both;
}
.add_new_faq{float:left;}
.upload {
border:0px solid #000000;
}

</style>
<%= form_for(faq, :url => program_faq_path(@program, faq), :method => :put) do |fa| %>
  <%= hidden_field_tag "count", count%>
  <div style="margin-bottom: 10px;"><%= fa.text_field :question , :class => "autogrow form-control", :placeholder => "Type your question here" %></div>
  <div style="margin-bottom: 0;" class="new-status-box"><%= fa.text_area :answer ,:placeholder => "Type your answer to the question here", :id => "faq_answer_#{count}" %></div>

  <div class="link_box" style="margin-top:8px;">
    <span class="img_link_lbl">Image Link:</span>
    <span class="vid_link_lbl">Youtube / Vimeo Link:</span>
    <span class="l_link_lbl">Link or File:</span>
    <span class="gallery_link_lbl">Pictures:</span>
    <span class="l_link_lbl vid_link_lbl img_link_lbl gallery_link_lbl">
      <%= fa.text_field :link, :class => "file_url form-control" %>
    </span>
    <span class="l_link_lbl img_link_lbl gallery_link_lbl upload">
    OR <%= fa.file_field :attachment %>
    </span>
  </div>
<div class="box-content-bottom">
  <%= link_to image_tag("ico-image.png"), "#", :class => "addImage", :name => "img_link_lbl" %>
  <%= link_to image_tag("ico-video.png"), "#", :class => "addImage", :name => "vid_link_lbl" %>
  <%= link_to image_tag("ico-link.png"), "#", :class => "addImage", :name => "l_link_lbl" %>
  <%= link_to image_tag("ico-gallery.png"), "#", :class => "addImage", :name => "gallery_link_lbl" %>

  <a href="#" class="showNewTagCont" style="margin-top:10px;"><img src="/images/ico-tag.png" alt="Ico-tag"></a>

  <div style="margin-left: 10px; display:inline;">
    <span class="newTag" style="display:none">
    <%= fa.text_field :tags, class: "newtag newTagVal", placeholder: "+ add tag", style: "margin-left: 10px; width: 100px;margin_top:0px;" %>
    </span>
  </div>

  <span class= "pull-right"> <%= fa.collection_select :role_code, RoleType.on_programs, :code, :name, {:prompt => 'Relevant to'}, :class=>"form-control", :style=>"margin-right:0;" %> </span>

  <% relevant_pages = %w(summary_page community_page mentors_page applicants_page pitch_detail_page milestone_page project_feed_page documents_page feedback_page team_page activity_page setup_page manage_program_page) %>
  <span class= "pull-right"> <%= fa.collection_select :relevant_page, relevant_pages, :to_s, :titleize, {:include_blank => 'Tag to'}, :class=>"form-control", :style=>"margin-right:0;" %> </span>
	<div class="clear"></div>
</div>

<div class="clr"></div>
<div>
  <div class="clr"></div>
  <div class="pull-right"><%= fa.submit "Save", :id => "submit" %></div>
</div>
<% end %>

app/views/faqs/_edit_ecosystem_faq.html.erb
<style type="text/css">
  .clr {
    clear: both;
}
.add_new_faq{float:left;}
.upload {
border:0px solid #000000;
}

</style>
<%= form_for(faq, :url => faq_update_organisation_path(@organisation, :faq_id => faq.id), :method => :put) do |fa| %>
  <div style="margin-bottom: 10px;"><%= fa.text_field :question , :class => "autogrow form-control", :placeholder => "Type your question here" %></div>
  <div style="margin-bottom: 0;" class="new-status-box"><%= fa.text_area :answer ,:placeholder => "Type your answer to the question here", :id => "eco_faq_#{count}" %></div>

  <div class="link_box" style="margin-top:8px;">
    <span class="img_link_lbl">Image Link:</span>
    <span class="vid_link_lbl">Youtube / Vimeo Link:</span>
    <span class="l_link_lbl">Link or File:</span>
    <span class="gallery_link_lbl">Pictures:</span>
    <span class="l_link_lbl vid_link_lbl img_link_lbl gallery_link_lbl">
      <%= fa.text_field :link, :class => "file_url form-control" %>
    </span>
    <span class="l_link_lbl img_link_lbl gallery_link_lbl upload">
    OR <%= fa.file_field :attachment %>
    </span>
  </div>
<div class="box-content-bottom">
  <%= link_to image_tag("ico-image.png"), "#", :class => "addImage", :name => "img_link_lbl" %>
  <%= link_to image_tag("ico-video.png"), "#", :class => "addImage", :name => "vid_link_lbl" %>
  <%= link_to image_tag("ico-link.png"), "#", :class => "addImage", :name => "l_link_lbl" %>
  <%= link_to image_tag("ico-gallery.png"), "#", :class => "addImage", :name => "gallery_link_lbl" %>

  <a href="#" class="showNewTagCont" style="margin-top:10px;"><img src="/images/ico-tag.png" alt="Ico-tag"></a>

  <div style="margin-left: 10px; display:inline;">
    <span class="newTag" style="display:none">
    <%= fa.text_field :tags, class: "newtag newTagVal", placeholder: "+ add tag", style: "margin-left: 10px; width: 100px;margin_top:0px;" %>
    </span>
  </div>

  <% relevant_pages = %w(eco_summary_page) %>
  <span class= "pull-right"> <%= fa.collection_select :relevant_page, relevant_pages, :to_s, :titleize, {:include_blank => 'Tag to', :selected => 'eco_summary_page'}, :class=>"form-control", :style=>"margin-right:0;" %> </span>
	<div class="clear"></div>
</div>

<div class="clr"></div>
<div>
  <div class="clr"></div>
  <div class="pull-right"><%= fa.submit "Save", :id => "submit" %></div>
</div>
<% end %>

app/views/faqs/_faqs.html.erb
<div class="row main-row">
<div class="col-md-10 main-right-section">
  <a href="sec2" name="sec2" class="section_nav"></a>
  <h1 id="faq_list_title">FAQ List (<%= @faqs.count %>) </h1>
<br />
  <% count = 1; @faqs.each do |faq| %>
  <div class="faq_count_<%= count%>" style="margin-left:25px;">
    <div class="newsentry faq_<%= count%>" style="margin-left:25px;">
      <div class="faq_bg">
        <h2 class="titleLine"><b>Question <%= count %>:</b> <%= faq.question %>
          <p class="pull-right edit_faq " id=<%= count%> style="cursor:pointer"><b>Edit</b></p>
        </h2>
        <p><b>Answer:</b> <%= faq.answer.html_safe %></p>
          <% if faq.attachment.present? %>
            <% file = faq.attachment_url.split(".")[-1] %>
            <% if ["jpeg","jpg","png","gif"].include?(file.downcase) %>
              <%= image_tag faq.attachment, :style => "width: 100%;" %>
            <% elsif ["pdf"].include?(file.downcase) %>
              <b>Link URl: </b><%= link_to("#{root_url}#{faq.attachment}", "#{root_url}#{faq.attachment_url}", :target =>"_blank", :class => 'text_underline') %>     
<!--               <iframe src="/pdfjs/web/viewer.html?file=<%= faq.attachment %>" style="border: 0" width="100%" height="400" frameborder="0" scrolling="no"></iframe> -->
            <% else %>
              <b>Link URl: </b><%= link_to("#{root_url}#{faq.attachment}", "#{root_url}#{faq.attachment_url}", :target =>"_blank", :class => 'text_underline') %>
            <% end %>
          <% end %>

          <% if faq.link.present? %>
            <% file = faq.link.split(".")[-1] %>
            <% if ["jpeg","jpg","png","gif"].include?(file.downcase) %>
              <%= image_tag faq.link, :style => "width: 400px;" %>
            <% elsif faq.link.match("youtube")%>
              <% video_id = faq.link.split("v=")[-1] %>
              <b>Link URl: </b><%= link_to(faq.link, faq.link, :target =>"_blank", :class => 'text_underline') %><br><br/>

              <iframe width="100%" height="315" src="//www.youtube.com/embed/<%= video_id %>" frameborder="0" allowfullscreen></iframe>
            <% elsif faq.link.match("vimeo")%>
              <b>Link URl: </b><%= link_to(faq.link, faq.link, :target =>"_blank", :class => 'text_underline') %><br><br/>
              <% video_id = faq.link.split("/")[-1] %>
              <iframe src="//player.vimeo.com/video/<%= video_id %>?badge=0&amp;color=e64067" width="100%" height="315" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 
            <% elsif ["pdf"].include?(file.downcase)%>
              <b>Link URl: </b><%= link_to("#{faq.link}", faq.link, :target =>"_blank", :class => 'text_underline') %>              
<!--               <iframe src="z/pdfjs/web/viewer.html?file=<%#= faq.link %>" style="border: 0" width="100%" height="400" frameborder="0" scrolling="no"></iframe> -->
            <% else%>
              <b>Link URl: </b><%= link_to("#{root_url}#{faq.link}", faq.link, :target =>"_blank", :class => 'text_underline') %>
            <% end %>
          <% end %>
          
      </div>
		<div class="actions feed-actions">

<span class="pull-right"><%= link_to image_tag("ico_trash.png"), program_faq_path(:id => faq.id), :title =>"Delete", :confirm => 'Are you sure?', :method => :delete, :class=>"delFeed" %></span>
<div class="clear"></div>
</div>
    </div>
    <div class="block edit_<%= count%>" style="display:none">
      <%= render "edit", :faq => faq, :count=> count%>
    </div>
    </div>
    <% count+=1 %>
  <% end %>
</div>
</div>

app/views/faqs/new.html.erb
<% content_for :title do %>
  <%= "#{context_program.try(:title)} - Admin - Faqs" %>
<% end %>
<% page = "setup_program"; ppage = "faq"%>
<%= render "shared/bs_navbar", :page => page, :ppage => ppage %>

<%#= render "shared/navbar", :page => "setup_program" %>
<%#= render "shared/program_setup_sidebar", :page => "program" %>
<div class="row page_head">
  <div class="col-md-8">
    <h3>
      <i class="gn-icon gn-icon-question gn-icon-large"></i>
      Faqs
      <i class="glyphicon glyphicon-question-sign help-sign" data-toggle="tooltip" data-placement="bottom" title="FAQ lets you create customised contextual help on the various pages of the platform"></i>
    </h3>
  </div>
  <div class="col-md-4 breadcrumb">
    <a href="#"><%=context_program.title%></a> / <a href=<%= context_program.try(:persisted?) ? edit_program_url(context_program) : new_program_url %>>Setup</a> / <a href="#" class="active_bread">Faqs</a>
  </div>
</div>
<div class="row main-row">
	<div class="col-md-10 main-right-section">
		<%= render "shared/flash" %>
		<a href="sec1" name="sec1" class="section_nav"></a>
		<h2 class="titleLine title-normal"><span>Main section</span></h2>
	<%= nested_form_for(@program, :html => {:class => "reqForm no_float", :style => "margin-left: 20px" }) do |f| %>
    <%= render "form", :f => f %>
	<% end %>
</div>
  <div class="col-md-2 stick_me">
    <ul class="navigator-menu">
      <li id="nav_sec1" class="active-navigator-title">
        <p>Main Section</p>
        <ul>
          <li><a href="#sec1">Create FAQ</a></li>
          <li><a href="#sec2">FAQ List</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

<%= render "faqs", :faqs => @faqs %>

<%= javascript_include_tag "jquery.sticky-kit.min" %>
<script type="text/javascript">
  jQuery(document).ready(function($){
    $(".stick_me").stick_in_parent({
      parent: $(".two_sides_content"),
      offset_top: 300
    });
    
    $('.help-sign').tooltip();
  });
  $('.navigator-menu li ul li a').click(function(){
      $('.navigator-menu li ul li').removeClass('active-navigator-section');
      $('.navigator-menu li').removeClass('active-navigator-title');
      $(this).parent().addClass('active-navigator-section');
      $(this).parent().parent().parent().addClass('active-navigator-title');
    $('html, body').animate({
        scrollTop: $('[name="' + $.attr(this, 'href').substr(1) + '"]').offset().top - 60
    }, 500);
    return false;
  });
  $("[rel=tooltip]").tooltip();
</script>

app/views/faqs/show.html.erb
<div id="rightcontent">
  <% cache @feeds do %>
  
    <% @faqs.each do |feed| %>
      <div class="newsentry ">
 
        <div class="box-content">
          <div class="textbox ">
            <%= feed.description %>
            <div class="carouselCont">
              <%= image_tag feed.attachment, :style => "width: 400px;" %>
              <% if feed.link.present? %>
                <% if !feed.link.scan(/~^(?:f|ht)tps?:/i).present? %>
                  <%= link_to("Visit link", "https://".concat(feed.link), target: "_blank", :class => 'text_underline') %>
                <% end  %>
              <% end %>
            </div>
          </div>
          <div class="actions ">
            <%#= feed_like_link(feed) %>
            <%#= link_to("<span class=\"anzahl\">#{feed.likes_count}</span> Likes".html_safe, "#", :class => "showLikes") %>
            <%#= link_to("<span class=\"anzahl\">#{feed.comments.count}</span> Comments".html_safe, "#", :class => "commentFeed") %>
            <%#= feature_link(feed) %>
            <%#= link_to image_tag("ico_trash.png"), polymorphic_path([@program, feed]), :method => :delete, :class => "delFeed" %>
          </div>
          <div class="feedLikes"></div>
          
          <%#= render "comments/inline_comments", :commentable => feed %>

          <%#= render "shared/comment_form", :comment => Comment.new, :commentable_type => feed.class.to_s, :commentable_id => feed.id %>
        </div>
        <div class="clr"></div>
      </div>
    <% end %>
  <% end %>
</div>