config/routes.rb
require 'resque/server'
require 'resque_scheduler'
require 'subdomain'
Resque::Scheduler.dynamic = true
Apptual::Application.routes.draw do

  get "programs/:id/search" => "search#index", :as => :index_search

  devise_for :users, :controllers => {:registrations => 
    "registrations", :invitations => 'invitations', :omniauth_callbacks => "users/omniauth_callbacks",
     :passwords => "passwords", :confirmations => 'confirmations'
  } do
      get  "/users/invitation/accept" => "invitations#accept"
      get  "/users/invitation/check_email" => "invitations#check_email"
      get  "/users/invitation/find_user" => "invitations#find_user"
      get  "/users/invitation/invite_existing" => "invitations#invite_existing"
  end
  
  devise_scope :user do
    get "/users/sign_up/step_2/:id" => "registrations#step_2", 
      :as => :step_2_user_registration
    get "/users/force/:id" => "registrations#force_sign_in", :as => :force_sign_in
    put "users/update_without_session/:id" => "registrations#update_without_session",
      :as => :update_without_session_registration
    get "/users/about_me" => "registrations#about_me", :as => :about_me_registration
    put "/users/update_about_me" => "registrations#update_about_me", :as => :update_about_me_registration
    put "/users/accept_invitation" => "registrations#accept_invitation", :as => :invitation_validation
    get "/profile/:id" => "registrations#show", :as => :user

    post 'users/omniauth_callbacks/create_twitter_user' => "users/omniauth_callbacks#create_twitter_user"
    get "/users/finish" => "registrations#finish", :as => :finish_registration
    get "users/show_faq" => "registrations#show_faq"
    get "users/pages_visited" => "registrations#pages_visited"
    put "/users/social_update" => "registrations#social_update", :as => :social_update
    get "/users/edit_user" => "registrations#edit_user", :as => :edit_user
    put "users/admin_update/:id" => "registrations#admin_update", :as => :admin_update
  end
  resources :organisations do
    get "/members/:role_code" => "organisations#members", :on => :member,
      :as => :members
    get   :eco_login,      on: :member
    get   :buzz,      on: :member
    post  :buzz_post, on: :member
    get   :popup_details,      on: :member
    resources :community_feeds, :only => [:destroy] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
    end
    resource :summary, :controller => :eco_summaries
    get :faqs,      on: :member    
    put :faq_save,      on: :member
    put :faq_update,      on: :member
    delete :faq_destroy,      on: :member
    post :contact_us, :on => :member
    resources :coupons, :only => [:index, :show, :create, :new, :destroy]
    resources :subscriptions, :only => [:edit, :create, :new, :update, :delete] do
      get   :soft_deleted_user,   on: :collection
    end
    
    get   :reactivate_account,  on: :collection
    get   :deactivate_account,  on: :collection

    get :badge_authority_details
    post :badge_authority_details_save
    
  end

  resources :comments, :only => [:create, :destroy] do
    put :like, :on => :member
    put :unlike, :on => :member
    get :like_from_mail, :on => :member
  end

  resources :surveys do
    resources :questions
  end

  resources :payments do
    get :plans, on: :collection
    get :subscriptions, on: :collection
    get :check_vat, on: :collection
    get :refund, on: :collection    
  end

  resources :ecosystems, :only => [:index, :show, :create, :new, :destroy]

  resources :user_contact_requests, :only => [:create]

  resources :programs do
    get "manage_form"
    put "manage_form_save"
    put "feed_form"
    get "change_feed_form"
    get :dashboard
    get :export_users_detail
    get :export_projects_detail
    get :download_phase_in_csv, :on => :member
    get :get_action_list
    get :community_tab
    put :update_custom_filter
    get :get_rule
    put :update_rule
    delete :delete_rule
    collection do
      post :contact_us
    end

    resources :voting_sheets, :only => :none do
      post :download,:on=>:collection
    end

    resources :messages, :only => :none do
      put :participants, :on => :collection
      put :pitches, :on => :collection
      put :mentor_pitches, :on => :collection
      put :phase_messages, :on => :collection
      put :msg_pitch_team, :on => :collection
      get :customize_email_messages, :on => :collection
      get :feedback_emails,:on=>:collection
      post :feedback_emails_save,:on=>:collection
      get :admin_invite ,:on=>:collection
      post :admin_invite_save ,:on => :collection
      get :team_member_invite ,:on=>:collection
      post :team_member_invite_save ,:on => :collection
      get :team_mentor_invite ,:on=>:collection
      post :team_mentor_invite_save ,:on => :collection
      get :comment_emails,:on=>:collection
      post :comment_emails_save,:on=>:collection
      get :mentor_offer_invite,:on=>:collection
      post :mentor_offer_invite_save,:on=>:collection
      get :join_team,:on=>:collection
      post :join_team_save,:on=>:collection
      get :submit_pitch,:on=>:collection
      post :submit_pitch_save,:on=>:collection
      get :collaboration_successfull,:on=>:collection
      post :collaboration_successfull_save,:on=>:collection
      get :download_csv,:on=>:collection
      get :join_team_email,:on=>:collection
      post :join_team_email_save,:on=>:collection
      get :declines_join_team_request,:on=>:collection
      post :declines_join_team_request_save,:on=>:collection
      get :rate_events_mail,:on=>:collection
      post :rate_events_mail_save,:on=>:collection
    end

    resources :customisations, :only => [:new, :create] do
      delete :delete_custom_fields, :on => :collection
      put :remove_basic_fields, on: :collection
    end

    resources :faqs, :only => [:new, :create, :show, :update, :destroy]
    resources :settings, :only => [:new, :create] do
      post :cloneable, on: :collection
    end

    resources :workflows, :only => [:index, :create] do
      put :toggle_status, on: :member
      put :achieved, on: :member
      put :undo, on: :member
      delete :delete_milestone, on: :member
    end

    resources :events do
      get :accept, :on => :member
      post :reject_participant, :on => :collection
      get :manage_participant, :on => :member
      get :confirm_participant, :on => :collection
      resources :event_sessions, :only => [:destroy] do
        get :export_event_session, :on => :member
        get :print_event_session, :on => :member
        post :message_all, :on => :collection
      end
    end

    resources :community_feeds, :only => [:index, :create, :destroy, :show] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
      put :non_sticky, :on => :member
      put :sticky, :on => :member
      put :remove_from_blog, :on => :member
      put :add_to_blog, :on => :member
      put :remove_from_eco_blog, :on => :member
      put :add_to_eco_blog, :on => :member
      get :like_from_mail, :on => :member
    end
    resource :summary, :controller => :program_summaries do
      get :authorize_eventbrite_account, :on => :member
      get :create_eventbrite_account, :on => :member
      put :add_eventbrite_user_key, :on => :member
      get :fetch_eventbrite_events, :on => :member
      post :create_eventbrite_events, :on => :member
      put :generate_nav_links, :on => :collection
    end
    resource :program_plans do
      get :attending, :on => :member
      get :not_attending, :on => :member
      get :attendees, :on => :member
    end
    resource :scope, :controller => :program_scopes
    resource :invitation, :controller => :program_invitations do
      get :invites, :on => :collection
      post :send_invites, :on => :collection
    end
    
    resource :due_diligence do
      get :judging_score, :on => :collection
      get :export_judging_details, :on => :collection
    end
    
    resources :phases, :only => :index do
      put :task_manager, :on => :collection
      post :task_manager, :on => :collection
      post :remind, :on => :collection
      post :message_all, :on => :collection
      get :manage, :on => :collection
      put :transition, :on => :collection
    end
    resources :pitches do
      post :iteration, :on => :member
      get :feeds, :on => :member
      get :team, :on => :member
      get :nudge, :on => :member
      get :be_mentor, :on => :member
      put :be_member, :on => :member
      get :join_team, :on => :member
      put :join_team, :on => :member
      put :invite_mentor, :on => :member
      get :contacts, :on => :member
      put :add_mentor, :on => :member
      put :remove_mentor, :on => :member
      put :add_membership_requester, :on => :member
      put :remove_membership_requester, :on => :member
      put :add_collaborater_requester, :on => :member
      put :remove_collaborater_requester, :on => :member
      put :shortlist, :on => :member
      put :finalist, :on => :member
      put :skills_needed, :on => :member
      post :due_diligence, :on => :member
      get :recommended_events, :on => :member
      put :assign_mentor, :on => :member
      delete :gallery_pic_remove, :on => :member
      
      resources :edit_pitch_field, :only => :none do
        get :toggle_edit_status, :on => :collection
      end
      
      resources :pitch_privacies, :only => [] do
        get :change_privacy_of_pitch, :on => :collection
      end
      
      resources :pitch_work_flow, :only => [] do
        get :check_required_fields, :on => :collection
      end
      
      get '/courses/:course_id/show' => "courses#show", as: :course_show
      post :refer_pitch_some_one, :on => :member
      post :be_collaborater, :on => :member
      resources :documents, :only => [:index, :create, :destroy] do

app/views/layouts/shared/_analytics.html.erb
<% if Rails.env == "production" %>
  <% domain_obj= mapped_url(request.host)%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-43037905-1', 'dojo.college');
    ga('create', "<%= domain_obj.try(:analytics_id) ? domain_obj.try(:analytics_id) : ''%>", "<%= domain_obj.try(:domain) ? domain_obj.try(:domain) : ''%>", {'name': 'newTracker' });

    ga('send', 'pageview');
    ga('newTracker.send', 'pageview');

  </script>
<% end %>

app/views/layouts/shared/_assets.html.erb
<%= javascript_include_tag "jquery-1.9.0" %>
<%= javascript_include_tag "jquery_ujs" %>
<%= stylesheet_link_tag 'css/summernote'%>
<%= stylesheet_link_tag    "css/bootstrap.css", :media => "all" %>
<%= stylesheet_link_tag 'css/summernote-bs2', :media => "all"%>
<%= stylesheet_link_tag    "css/bootstrap-theme.css", :media => "all" %>
<%= stylesheet_link_tag    "css/custom.css", :media => "all" %>
<%= stylesheet_link_tag    "css/font-awesome.css", :media => "all" %>
<%= stylesheet_link_tag    "jquery-ui-timepicker-addon", :media => "all" %>
<%= stylesheet_link_tag    "jquery-ui-1.10.0.custom.min", :media => "all" %>
<%= stylesheet_link_tag    "component", :media => "all" %>
<%= stylesheet_link_tag    "icomoon", :media => "all" %>
<%= stylesheet_link_tag    "owl.carousel", :media => "all" %>
<%= stylesheet_link_tag    "owl.theme", :media => "all" %>
<%= javascript_include_tag 'js/summernote.min'%>
<%= javascript_include_tag "js/bootstrap.js" %>
<%= javascript_include_tag "jquery-ui-1.10.0.custom.min" %>

<%= javascript_include_tag "jquery.collapsiblepanel" %>
<%= javascript_include_tag "jquery.placeholder" %>
<%= javascript_include_tag "jquery-ui.toogleSwitch" %>
<%= javascript_include_tag "jquery.carouFredSel-6.2.0-packed" %>
<%= javascript_include_tag "jquery.autogrow-textarea" %>
<%= javascript_include_tag "jquery.ui.selectmenu" %>

<%= javascript_include_tag "jquery.uploadify.min" %>
<%= stylesheet_link_tag    "uploadify", :media => "all" %>
<%= javascript_include_tag "flash.detect" %>
<%= javascript_include_tag "jquery.fancybox.pack.js?v=2.1.4" %>
<%= javascript_include_tag "nested_form" %>
<%= stylesheet_link_tag    "jquery.fancybox.css?v=2.1.4", :media => "all" %>
<%= stylesheet_link_tag    "jRating.jquery", :media => "all" %>
<%= stylesheet_link_tag    "jquery.bxslider.css", :media => "all" %>
<%= javascript_include_tag "jquery.easing.1.3" %>
<%= javascript_include_tag "jquery.fitvids" %>
<%= javascript_include_tag "jquery.bxslider" %>
<%= javascript_include_tag "jquery.bxslider.min" %>
<%= stylesheet_link_tag    "jquery.fancybox.css?v=2.1.4", :media => "all" %>




<%= javascript_include_tag "owl.carousel" %>


<%= javascript_include_tag "jRating.jquery.stefan.new" %>
<%= javascript_include_tag "jquery.form" %>

<%= stylesheet_link_tag    "redactor", :media => "all" %>
<%= javascript_include_tag "redactor.min" %>

<%= stylesheet_link_tag "jquery.minicolors", :media => "all" %>
<%= javascript_include_tag "jquery.minicolors.js" %>

<%= javascript_include_tag "jquery-ui-timepicker-addon" %>
<!--[if lt IE 9]>
	<script src="http://dev.dojo.college/wp-content/themes/apptual/js/html5.js" type="text/javascript"></script>
<![endif]-->
<link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag    "theme-my-login.css?ver=6.2.3", :media => "all" %>
<%= stylesheet_link_tag    "facebook-btn.css?ver=3.5", :media => "all" %>
<%= stylesheet_link_tag    "twitter-btn.css?ver=3.5", :media => "all" %>
<%= stylesheet_link_tag    "style.css?ver=3.5", :media => "all" %>
<link rel='prev' title='Programs &#8211; OLD' href='//dev.dojo.college/programs/' />
<link rel='next' title='Basics' href='//dev.dojo.college/register/basics/' />
<!--[if lt IE 9]>
  <%= javascript_include_tag "excanvas.min" %>
<![endif]-->

<%= javascript_include_tag "jquery.jqplot.min" %>
<%= javascript_include_tag "jqplot.dateAxisRenderer.min" %>
<%= javascript_include_tag "jqplot.canvasTextRenderer.min" %>
<%= javascript_include_tag "jqplot.canvasAxisTickRenderer.min" %>
<%= javascript_include_tag "jqplot.categoryAxisRenderer.min" %>

<%= javascript_include_tag "jqplot.barRenderer.min" %>
<%= javascript_include_tag "jqplot.canvasAxisLabelRenderer.min" %>

<%#= stylesheet_link_tag    "jquery.jqplot.min", :media => "all" %>

<%= javascript_include_tag "custom" %>
<%#= stylesheet_link_tag    "print", :media => "print" %>
<%= javascript_include_tag "colorup" %>
<%= javascript_include_tag "jquery.sticky" %>
<%= javascript_include_tag "masonry.pkgd.min" %>
<%= javascript_include_tag "jquery.autosize" %>
<%= stylesheet_link_tag    "alertifycss/alertify.default", :media => "all" %>
<%= stylesheet_link_tag    "alertifycss/alertify.bootstrap", :media => "all" %>
<%= stylesheet_link_tag    "alertifycss/alertify.core", :media => "all" %>
<%= javascript_include_tag "alertifyjs/alertify.min" %>
<%= javascript_include_tag "alertifyjs/alertify" %>
<%= javascript_include_tag "jquery.collapsiblepanel" %>
<%#= javascript_include_tag "jquery.easyui.min" %>
<%#= stylesheet_link_tag    "pick-a-color-1.2.3.min", :media => "all" %>
<%= javascript_include_tag "tinycolor-0.9.15.min" %>
<%= javascript_include_tag "pick-a-color-1.2.3.min.js" %>

<%#= stylesheet_link_tag    "css/slider", :media => "all" %>
<%= javascript_include_tag "bootstrap-slider" %>

<%#= stylesheet_link_tag    "css/slide_component", :media => "all" %>
<%= javascript_include_tag "html5shiv" %>
<%= javascript_include_tag "respond.min" %>

<%= javascript_include_tag "bootstrap-progressbar" %>
<link href='//fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<script src="//connect.facebook.net/en_US/all.js"></script>
<!--[if  IE 9]>
	<%= stylesheet_link_tag "ie_style", :media => "all" %>
<![endif]-->
<%= csrf_meta_tags %>

app/views/layouts/shared/_bs_header.html.erb
<%= stylesheet_link_tag    "style.css?ver=3.5", :media => "all" %>
<% @program ||= context_program%>
<% is_subdomain = valid_subdomain(current_subdomain)%>
<div class="site-header page-header main-header" id="masthead">
	<div class="page-header-inner">
			<% if user_signed_in? %>
	    <!--TODO: it should fetch company/program logo-->
  	    <% if !current_user.super_admin? && current_organisation.present? %>
  	    	<%= link_to_if(current_organisation, image_tag(current_organisation.avatar.logo.url), (is_subdomain ? root_url(subdomain: false) : root_url), :class => "companyLogo pull-left") %>
  	    <% elsif current_user and @prog %>
          <%= link_to(image_tag(@prog.try(:organisation).try(:avatar_url)), (is_subdomain ? root_url(subdomain: false) : root_url), :class => "companyLogo pull-left") %>
        <% else %>
  	    	<%= link_to(image_tag("logo-apptual.png"), (is_subdomain ? root_url(subdomain: false) : root_url), :class => "companyLogo pull-left") %>
		    <% end %>
			<% else %>
        <%if context_program %>
          <%= link_to(image_tag(context_program.organisation.avatar_url), (is_subdomain ? root_url(subdomain: false) : root_url), :class => "companyLogo pull-left") %>
        <% else %>
			   <%= link_to(image_tag("logo-apptual.png"), (is_subdomain ? root_url(subdomain: false) : root_url), :class => "companyLogo pull-left") %>
			  <% end %>
		  <% end %>

			<% if user_signed_in? && !current_user.super_admin? %>
			 <p class="company-slogan pull-left visible-lg"><%= current_organisation ? current_organisation.try(:slogan) : @prog.try(:organisation).try(:slogan) %></p>
		  <% elsif @program.present? %>
        <p class="company-slogan pull-left visible-lg"><%= @program.organisation.try(:slogan) %></p>
		  <% end %>
			
		<div class="menu-right pull-right">
		  <% if user_signed_in? %>
				<div class="dropdown pull-right">
				  <button class="btn dropdown-toggle select_prog_btn" type="button" id="dropdownMenu1" data-toggle="dropdown">
				    <%= current_user.first_name %>
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu top_right_menus" role="menu" aria-labelledby="dropdownMenu1">
				    <li>
				       <%= link_to("Settings", awaited_user.nil? ? ((is_subdomain ? edit_user_registration_url(subdomain: false) : edit_user_registration_url)) : "#") %>
					  </li>
					  	<%= render "layouts/shared/super_admin_options" if current_user.super_admin? %>
					  <li class="logout_link">
					    <%= link_to("Logout", (is_subdomain ? destroy_user_session_url(subdomain: false) : destroy_user_session_url), :method => :delete) %>
					  </li>
				  </ul>
				</div>

				<div id="select_action_container"  class="pull-right">
			    <div id="notification-block">
				    <div id="notifications">
							<div class="tablecell">
					    	<%= link_to(image_tag(current_user.avatar.thumb.url, :height => "40", :class => "img-circle img-responsive img-circle-border"), (is_subdomain ? user_url(current_user, subdomain: false) : user_url(current_user))) %>
						  </div>
			                <% if !context_program.blank? %>
			                	<%notification_count = notification_counts(context_program)%>
			                	<%project_id_feeds_present = project_id_feeds_present(context_program)%>
				              	<% if !current_user.pitch_invitations.empty? %>
				              		<%= link_to notification_count, "#all_invitations", id: "nfc_counter", class: " nfc_counter_open fancybox" %>
								<% elsif project_id_feeds_present.count > 1 %>
									<%= link_to notification_count, "#all_pitch_feeds", id: "nfc_counter", class: "fancybox" %>
								<% elsif project_id_feeds_present.count == 1 %>
									<%= link_to notification_count, polymorphic_url([context_program, :visited_notifications], :notification_url=>(is_subdomain ? polymorphic_url([:feeds, @program, feed_pitch(project_id_feeds_present.first)], subdomain: false) : polymorphic_url([:feeds, context_program, feed_pitch(project_id_feeds_present.first)])), type: "pitch"), :method=>"post", id: "nfc_counter", class: "" %>
								<% elsif notification_count > 0 %>
									<%= link_to notification_count, polymorphic_url([context_program, :visited_notifications], :notification_url=>program_community_feeds_path(context_program.id), type: "program"), :method=>"post", id: "nfc_counter", class: "" %>
								<% end %>
							<% end %>
					  </div>
					  <div class="clear"></div>
				  </div>
			  </div>
				<div class="dropdown pull-right">
				  <% if awaited_user.nil? %>
					  <button class="btn dropdown-toggle select_prog_btn" type="button" id="dropdownMenu2" data-toggle="dropdown" >
						<%= selected_program %>
						<span class="<%= (visible_programs.try(:count) && visible_programs.try(:count) > 1)  ? "caret" : "" %>"></span>
					  </button>
				  <% end %>
				  <ul class="dropdown-menu top_right_menus open_left" role="menu" aria-labelledby="dropdownMenu2">
				    <% visible_programs.each do |program| %>
              <% if program.master_program? && current_user.company_admin?(program.organisation) %>
 						    <li>
							    <nobr><%= link_to program.title, (is_subdomain ? edit_program_url(program, subdomain: false) : edit_program_url(program))%></nobr>
							  </li>
              <% elsif !program.master_program? %>
                <li>
                  <nobr><%= link_to program.title, (is_subdomain ? edit_program_url(program, subdomain: false) : edit_program_url(program)) %></nobr>
                </li>
              <% end %>
				  	<% end if visible_programs.try(:count) > 1 %>
				  	<% if need?(["company_admin", "program_admin"], current_organisation) %>
						  <li class="create_program_link">
						  	<%= link_to "+ Create Program", (is_subdomain ? new_program_url(subdomain: false) : new_program_url) %>
						  </li>
					  <% end %>
				  </ul>
				</div>

			  <!--<div id="select_prog_container" class="pull-left">
			    <div id="select_prog_btn">
			      <div class="inner"><nobr><%= selected_program %></nobr></div>
					  <ul id="select_prog_list">
					  	<%# visible_programs.each do |program| %>
						    <li>
							    <nobr><%#= link_to program.title, edit_program_path(program) %></nobr>
							  </li>
					  	<%# end %>
					  	<%# if need?(["company_admin"], current_organisation) %>
							  <li class="create_program_link">
							  	<%#= link_to "+ Create Program", new_program_path %>
							  </li>
						  <%# end %>
					  </ul>
				  </div>
			  </div>-->
          <% if current_user.pitch_invitations.any? %>
            <div style="display: none" id="all_invitations">
              <div class="lightbox_box">
                <% current_user.pitch_invitations.each_with_index do |invitation, i| %>
                  <h2><%= invitation.invitee_type == "collaborator" ? "Collaboration Request" : "Invitations to provide support to the #{t('pitch', 'p')}" %></h2>
                  <h3 class="iter_heading"><%= "By #{invitation.invited_by.full_name} on #{invitation.created_at.date_month_year}"%></h3>
                  <div class="previous_iterations">
                    <% if invitation.invitee_type == "collaborator"%>
                      <%= link_to "You have received a collaboration request", invitation_link(invitation), :class => "text_underline" %>
                      <%#= collaboration_msg(invitation) %>
                    <% else%>
                      <%= link_to "#{invitation.pitch.title}", invitation_link(invitation)%>
                      <div class="pull-right" style="margin-left: 10px;">
                        <%= link_to 'Decline', invitation_decline_link(invitation), :method => invitation.invitee_type == "collaborator" ? :put : :get, :class => "btn btn-xs btn-info"%>
                      </div>
                      <div class="pull-right">
                        <%= link_to 'Accept', invitation_accept_link(invitation), :method => invitation.invitee_type == "collaborator" ? :put : :get, :class => "btn btn-xs btn-info"%>
                      </div>
                    <% end %>
                  </div> 
                <% end %>
              </div>
            </div>
          <% end %>
          <% if !context_program.blank? && project_id_feeds_present.count > 1 %>
			<div style="display: none" id="all_pitch_feeds">
				<div class="lightbox_box">
				  <h2>Pitch Feed Notifications</h2>
				  <% feed_pitches(project_id_feeds_present).each_with_index do |pitch, i| %>
				    <h3 class="iter_heading"><%=i+1%>. <%= pitch.title%> feed updates</h3>
				        <div class="pull-right">
				          <%= link_to 'Visit Pitch Feeds', polymorphic_url([context_program, :visited_notifications], :notification_url=>(is_subdomain ? polymorphic_url([:feeds, @program, pitch], subdomain: false) : polymorphic_url([:feeds, context_program, feed_pitch(project_id_feeds_present.first)])), type: "pitch"), :method=>"post", :class => "btn btn-xs btn-info"%>
				        </div>
				  <% end %>
				</div>
			</div>
          <% end %>
		    <div class="clr"></div>
		  <% else %>
			  <%#= render "layouts/shared/login_form" %>
        <%= link_to "Login", (@program ? (is_subdomain ? program_login_program_url(@program, subdomain: false) : program_login_program_url(@program)) : (is_subdomain ? root_url(subdomain: false) : root_url)), style:"color:white;",class: "pull-right login-sum-btn" if controller_name == "dashboards" and !user_signed_in?%>
		  <% end %>
		</div>
<div class="clr"></div>
	</div>
</div>

app/views/layouts/shared/_flash_message.html.erb
<% if notice.present? %>
  <p class="message alert alert-warning">
    <%= notice %>
  </p>
<% elsif alert.present? %>
  <p class="error alert alert-danger">
    <%= alert %>
  </p>
<% end %>

app/views/layouts/shared/_login_form.html.erb
<% is_subdomain = valid_subdomain(current_subdomain)%>
<%= form_tag((is_subdomain ? new_user_session_url(subdomain: false) : new_user_session_url), :role=>"form", id: "login_form") do %>
  <%= content_tag :div, class: "form-group" do%>
    <%= label_tag(:email, "E-Mail")%>
    <%= text_field_tag(:email, nil, id: :user_login, class: "form-control", name: "user[email]") %>
  <% end %>
  <%= content_tag :div, class: "form-group" do%>
    <%= label_tag(:password, "Password")%>
    <%= password_field_tag(:password, nil, id: :user_pass, class: "form-control", name: "user[password]") %>
  <% end %>
  <%= content_tag :div, class: "form-group" do%>
    <%= link_to "Lost password", (is_subdomain ? new_password_url("user", subdomain: false) : new_password_url("user")), style:"font-size: 12px;" %><br />
  <% end %>
  <%= submit_tag "Login", id: "submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/shared/_super_admin_options.html.erb
<li>
  <%= link_to("Manage Organisations", polymorphic_path([:admin, Organisation])) %>
</li>