config/routes.rb
require 'resque/server'
require 'resque_scheduler'
require 'subdomain'
Resque::Scheduler.dynamic = true
Apptual::Application.routes.draw do

  get "programs/:id/search" => "search#index", :as => :index_search

  devise_for :users, :controllers => {:registrations => 
    "registrations", :invitations => 'invitations', :omniauth_callbacks => "users/omniauth_callbacks",
     :passwords => "passwords", :confirmations => 'confirmations'
  } do
      get  "/users/invitation/accept" => "invitations#accept"
      get  "/users/invitation/check_email" => "invitations#check_email"
      get  "/users/invitation/find_user" => "invitations#find_user"
      get  "/users/invitation/invite_existing" => "invitations#invite_existing"
  end
  
  devise_scope :user do
    get "/users/sign_up/step_2/:id" => "registrations#step_2", 
      :as => :step_2_user_registration
    get "/users/force/:id" => "registrations#force_sign_in", :as => :force_sign_in
    put "users/update_without_session/:id" => "registrations#update_without_session",
      :as => :update_without_session_registration
    get "/users/about_me" => "registrations#about_me", :as => :about_me_registration
    put "/users/update_about_me" => "registrations#update_about_me", :as => :update_about_me_registration
    put "/users/accept_invitation" => "registrations#accept_invitation", :as => :invitation_validation
    get "/profile/:id" => "registrations#show", :as => :user

    post 'users/omniauth_callbacks/create_twitter_user' => "users/omniauth_callbacks#create_twitter_user"
    get "/users/finish" => "registrations#finish", :as => :finish_registration
    get "users/show_faq" => "registrations#show_faq"
    get "users/pages_visited" => "registrations#pages_visited"
    put "/users/social_update" => "registrations#social_update", :as => :social_update
    get "/users/edit_user" => "registrations#edit_user", :as => :edit_user
    put "users/admin_update/:id" => "registrations#admin_update", :as => :admin_update
  end
  resources :organisations do
    get "/members/:role_code" => "organisations#members", :on => :member,
      :as => :members
    get   :eco_login,      on: :member
    get   :buzz,      on: :member
    post  :buzz_post, on: :member
    get   :popup_details,      on: :member
    resources :community_feeds, :only => [:destroy] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
    end
    resource :summary, :controller => :eco_summaries
    get :faqs,      on: :member    
    put :faq_save,      on: :member
    put :faq_update,      on: :member
    delete :faq_destroy,      on: :member
    post :contact_us, :on => :member
    resources :coupons, :only => [:index, :show, :create, :new, :destroy]
    resources :subscriptions, :only => [:edit, :create, :new, :update, :delete] do
      get   :soft_deleted_user,   on: :collection
    end
    
    get   :reactivate_account,  on: :collection
    get   :deactivate_account,  on: :collection

    get :badge_authority_details
    post :badge_authority_details_save
    
  end

  resources :comments, :only => [:create, :destroy] do
    put :like, :on => :member
    put :unlike, :on => :member
    get :like_from_mail, :on => :member
  end

  resources :surveys do
    resources :questions
  end

  resources :payments do
    get :plans, on: :collection
    get :subscriptions, on: :collection
    get :check_vat, on: :collection
    get :refund, on: :collection    
  end

  resources :ecosystems, :only => [:index, :show, :create, :new, :destroy]

  resources :user_contact_requests, :only => [:create]

  resources :programs do
    get "manage_form"
    put "manage_form_save"
    put "feed_form"
    get "change_feed_form"
    get :dashboard
    get :export_users_detail
    get :export_projects_detail
    get :download_phase_in_csv, :on => :member
    get :get_action_list
    get :community_tab
    put :update_custom_filter
    get :get_rule
    put :update_rule
    delete :delete_rule
    collection do
      post :contact_us
    end

    resources :voting_sheets, :only => :none do
      post :download,:on=>:collection
    end

    resources :messages, :only => :none do
      put :participants, :on => :collection
      put :pitches, :on => :collection
      put :mentor_pitches, :on => :collection
      put :phase_messages, :on => :collection
      put :msg_pitch_team, :on => :collection
      get :customize_email_messages, :on => :collection
      get :feedback_emails,:on=>:collection
      post :feedback_emails_save,:on=>:collection
      get :admin_invite ,:on=>:collection
      post :admin_invite_save ,:on => :collection
      get :team_member_invite ,:on=>:collection
      post :team_member_invite_save ,:on => :collection
      get :team_mentor_invite ,:on=>:collection
      post :team_mentor_invite_save ,:on => :collection
      get :comment_emails,:on=>:collection
      post :comment_emails_save,:on=>:collection
      get :mentor_offer_invite,:on=>:collection
      post :mentor_offer_invite_save,:on=>:collection
      get :join_team,:on=>:collection
      post :join_team_save,:on=>:collection
      get :submit_pitch,:on=>:collection
      post :submit_pitch_save,:on=>:collection
      get :collaboration_successfull,:on=>:collection
      post :collaboration_successfull_save,:on=>:collection
      get :download_csv,:on=>:collection
      get :join_team_email,:on=>:collection
      post :join_team_email_save,:on=>:collection
      get :declines_join_team_request,:on=>:collection
      post :declines_join_team_request_save,:on=>:collection
      get :rate_events_mail,:on=>:collection
      post :rate_events_mail_save,:on=>:collection
    end

    resources :customisations, :only => [:new, :create] do
      delete :delete_custom_fields, :on => :collection
      put :remove_basic_fields, on: :collection
    end

    resources :faqs, :only => [:new, :create, :show, :update, :destroy]
    resources :settings, :only => [:new, :create] do
      post :cloneable, on: :collection
    end

    resources :workflows, :only => [:index, :create] do
      put :toggle_status, on: :member
      put :achieved, on: :member
      put :undo, on: :member
      delete :delete_milestone, on: :member
    end

    resources :events do
      get :accept, :on => :member
      post :reject_participant, :on => :collection
      get :manage_participant, :on => :member
      get :confirm_participant, :on => :collection
      resources :event_sessions, :only => [:destroy] do
        get :export_event_session, :on => :member
        get :print_event_session, :on => :member
        post :message_all, :on => :collection
      end
    end

    resources :community_feeds, :only => [:index, :create, :destroy, :show] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
      put :non_sticky, :on => :member
      put :sticky, :on => :member
      put :remove_from_blog, :on => :member
      put :add_to_blog, :on => :member
      put :remove_from_eco_blog, :on => :member
      put :add_to_eco_blog, :on => :member
      get :like_from_mail, :on => :member
    end
    resource :summary, :controller => :program_summaries do
      get :authorize_eventbrite_account, :on => :member
      get :create_eventbrite_account, :on => :member
      put :add_eventbrite_user_key, :on => :member
      get :fetch_eventbrite_events, :on => :member
      post :create_eventbrite_events, :on => :member
      put :generate_nav_links, :on => :collection
    end
    resource :program_plans do
      get :attending, :on => :member
      get :not_attending, :on => :member
      get :attendees, :on => :member
    end
    resource :scope, :controller => :program_scopes
    resource :invitation, :controller => :program_invitations do
      get :invites, :on => :collection
      post :send_invites, :on => :collection
    end
    
    resource :due_diligence do
      get :judging_score, :on => :collection
      get :export_judging_details, :on => :collection
    end
    
    resources :phases, :only => :index do
      put :task_manager, :on => :collection
      post :task_manager, :on => :collection
      post :remind, :on => :collection
      post :message_all, :on => :collection
      get :manage, :on => :collection
      put :transition, :on => :collection
    end
    resources :pitches do
      post :iteration, :on => :member
      get :feeds, :on => :member
      get :team, :on => :member
      get :nudge, :on => :member
      get :be_mentor, :on => :member
      put :be_member, :on => :member
      get :join_team, :on => :member
      put :join_team, :on => :member
      put :invite_mentor, :on => :member
      get :contacts, :on => :member
      put :add_mentor, :on => :member
      put :remove_mentor, :on => :member
      put :add_membership_requester, :on => :member
      put :remove_membership_requester, :on => :member
      put :add_collaborater_requester, :on => :member
      put :remove_collaborater_requester, :on => :member
      put :shortlist, :on => :member
      put :finalist, :on => :member
      put :skills_needed, :on => :member
      post :due_diligence, :on => :member
      get :recommended_events, :on => :member
      put :assign_mentor, :on => :member
      delete :gallery_pic_remove, :on => :member
      
      resources :edit_pitch_field, :only => :none do
        get :toggle_edit_status, :on => :collection
      end
      
      resources :pitch_privacies, :only => [] do
        get :change_privacy_of_pitch, :on => :collection
      end
      
      resources :pitch_work_flow, :only => [] do
        get :check_required_fields, :on => :collection
      end
      
      get '/courses/:course_id/show' => "courses#show", as: :course_show
      post :refer_pitch_some_one, :on => :member
      post :be_collaborater, :on => :member
      resources :documents, :only => [:index, :create, :destroy] do

app/models/organisation.rb
class Organisation
  include Mongoid::Document
  include Mongoid::Timestamps
  include Sunspot::Mongoid2
  after_save :reindex_organisation
  before_destroy :reindex_organisation

  searchable do
    string :id
    text :company_name
    text :industry
    text :type
    text :type_of
    text :description
  end

  mount_uploader :avatar, AvatarUploader

  after_save :assign_admins
  before_create :assign_owner

  TYPES = {"enterprise" => "Enterprise", "non_profit" => 
    "Education/Government/NonProfit"}

  attr_protected :activate

  field :slogan,                :type => String, :default => ""
  field :manubar_color,         :type => String, :default => "#07B291"
  field :background_color,      :type => String, :default => "#333"
  field :type_of,               :type => String, :default => ""
  field :company_name,          :type => String, :default => ""
  field :industry,              :type => String
  field :description,           :type => String
  field :size,                  :type => String
  field :type,                  :type => String
  #stores user ids
  field :admins,                :type => Array, :default => []
  field :activate,              :type => Boolean, :default => false

  has_one :badge_authority, :dependent => :destroy

  has_one :address, :dependent => :destroy
  accepts_nested_attributes_for :address, reject_if: :all_blank

  has_many :programs, :dependent => :destroy
  has_one  :domain_map, :dependent => :destroy
  has_many :surveys, :dependent => :destroy

  has_many :subscriptions, :dependent => :destroy
  has_many :coupons, :dependent => :destroy

  belongs_to :owner, :class_name => "User"
  has_one :eco_summary, :dependent => :destroy
  has_many :faqs, :dependent => :destroy
  has_many :community_feeds, :dependent => :destroy
  accepts_nested_attributes_for :faqs, reject_if: :all_blank

  validates :company_name, :presence => true

  scope :for, lambda{ |user| where(:admins.in => [user.id.to_s]) }

  #INDEXES
  index({ company_name: 1 }, { unique: true, background: true })
  index({ admins: 1 }, { background: true })
  index({ owner: 1 }, { background: true })
  
  SIZE = [ "Less than 10 employees", "11 to 50 employees", "51 to 250 employees", "251 to 1000 employees", "1001 to 10000 employees", "10000+ employees"]
  TYPE = [ "Business", "Not for profit", "Membership organisation", "Public sector", "Local Authority", "Incubator / Innovation Cluster", "LEP"]

  def toggle_status!
    status = !activate
    update_attribute(:activate, status)
    owner.update_attribute(:approved, status)
    Resque.enqueue(App::Background::SendApprovalMessageToAdmin, owner.try(:id), id) if status
  end

  def owner?(user_id)
    owner_id == user_id
  end

  def title
    company_name
  end

  def type_of
    TYPES[read_attribute(:type_of)]
  end

  def build_invitations(mails, for_role, admin_invitor_id)
    invitations_to = mails[:company_admin].split(",").reject(&:blank?)
    invitation_message = mails[:invite_mail]
    invitations_to.each do |invitation|
      if invitation and invitation.strip.match Devise::email_regexp
        User.invite_user_admin(invitation, self, for_role, invitation_message, admin_invitor_id)
      end
    end
  end

  def add_admin!(user_id)
    admins << user_id
    save!
  end

  def to_s
    "Organisation: #{company_name}"
  end

  private 

  def assign_admins
    users = User.find(self.admins)
    RoleType.on_organisation.each do |type|
      users.each do |user|
        user.add_role(type.to_s, self.id.to_s)
      end
    end
  end

  def assign_owner
    self["owner_id"] = self["admins"].first
  end

  def reindex_organisation
    if self.changed?
      Resque.enqueue(App::Background::SolrIndexing, self.class.to_s, self.id)
    end
  end

end

app/controllers/admin/organisations_controller.rb
class Admin::OrganisationsController < ApplicationController

  before_filter :authorize_super_admin

  def index
    @page = "index"
    @organisations = Organisation.all
  end

  def setup
  	@page = "setup"
  end

  def customize_email
    @page = "setup"
  end

  def role_invitation
    @page = "setup"
    if !ProgramInvitation.blank?
      @program_invitation_mails=ProgramInvitationMail.where(:role_type => "super_admin").last
    end
  end

  def role_invitation_save
    @page = "setup"
    if ProgramInvitationMail.where(:role_type => "super_admin").last.present?
      @invitation_mail = ProgramInvitationMail.where(:role_type => "super_admin").last
      @invitation = @invitation_mail.update_attributes(:applicant_message => params[:message][:applicant], :selectors_message => params[:message][:selectors], :panel_message => params[:message][:panel], :mentors_message => params[:message][:mentors], :role_type => "super_admin")
    else
      @invitation_mail = ProgramInvitationMail.create(:applicant_message => params[:message][:applicant], :selectors_message => params[:message][:selectors], :panel_message => params[:message][:panel], :mentors_message => params[:message][:mentors], :role_type => "super_admin")
    end
      flash[:notice] = "Program invitation updated successfully."
      redirect_to :back
  end

  def toggle
    @organisation = Organisation.find(params[:id])
    @organisation.toggle_status!
    redirect_to :action => :index
  end
end

app/helpers/admin/organisations/customize_email_helper.rb
module Admin::Organisations::CustomizeEmailHelper
end

app/helpers/admin/organisations_helper.rb
module Admin::OrganisationsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
  def tags_for_filter_eco
    (CommunityFeed.feed_for_ecosystem(current_organisation).for_pitch(nil).pluck(:tags)).flatten.reject(&:empty?).uniq
  end

  def display_eco_blog?
    !eco_blog_posts.blank? && @organisation.try(:eco_summary).try(:eco_summary_customization).present? && @organisation.eco_summary.eco_summary_customization.blog == true
  end

  def eco_blog_posts
    CommunityFeed.blog_feed_for_organisation(@organisation.id, ["all"])
  end

end

app/views/admin/organisations/customize_email/admin_invite.html.erb
<div id="mainnavi">
	<%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
 	<%= render "admin/organisations/setup_header" %>
</div>

<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag admin_invite_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/admin_invite_form" %>
<% end %>
</div>

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_admin_invite');
});
$('#admin-hint').on('click', function(e){
    $("#admin-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#admin-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/comment_emails.html.erb
<div id="mainnavi">
	<%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
 	<%= render "admin/organisations/setup_header" %>
</div>

<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag comment_emails_save_admin_organisations_customize_email_index_path, :method => :post do %>
    <%= render "messages/comment_form" %>
<% end %>
</div>

<script>
         jQuery('.open_div_admin_comment').click(function(){
                var cont = $(this).attr("name");
                var has = $(this).hasClass("link_opened_div_in");
                $(".open_div_admin_comment").removeClass("link_opened_div_in")
                $(".closable_div_admin_comment").hide();
                if(has != true){
                        $(this).addClass("link_opened_div_in");
                        $("."+cont).show();
                        $("#"+cont).show();
                }
                return false;        
        });

         jQuery('.open_div_participant_comment').click(function(){
                var cont = $(this).attr("name");
                var has = $(this).hasClass("link_opened_div_in");
                $(".open_div_participant_comment").removeClass("link_opened_div_in")
                $(".closable_div_participant_comment").hide();
                if(has != true){
                        $(this).addClass("link_opened_div_in");
                        $("."+cont).show();
                        $("#"+cont).show();
                }
                return false;        
        });


         jQuery('.open_div_selector_comment').click(function(){
                var cont = $(this).attr("name");
                var has = $(this).hasClass("link_opened_div_in");
                $(".open_div_selector_comment").removeClass("link_opened_div_in")
                $(".closable_div_selector_comment").hide();
                if(has != true){
                        $(this).addClass("link_opened_div_in");
                        $("."+cont).show();
                        $("#"+cont).show();
                }
                return false;        
        });

        jQuery('.open_div_mentor_comment').click(function(){
                var cont = $(this).attr("name");
                var has = $(this).hasClass("link_opened_div_in");
                $(".open_div_mentor_comment").removeClass("link_opened_div_in")
                $(".closable_div_mentor_comment").hide();
                if(has != true){
                        $(this).addClass("link_opened_div_in");
                        $("."+cont).show();
                        $("#"+cont).show();
                }
                return false;        
        });


        jQuery('.open_div_panel_comment').click(function(){
                var cont = $(this).attr("name");
                var has = $(this).hasClass("link_opened_div_in");
                $(".open_div_panel_comment").removeClass("link_opened_div_in")
                $(".closable_div_panel_comment").hide();
                if(has != true){
                        $(this).addClass("link_opened_div_in");
                        $("."+cont).show();
                        $("#"+cont).show();
                }
                return false;        
        });

bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_admin_comment_admin');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_admin_comment_participant');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_admin_comment_selector');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_admin_comment_mentor');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_admin_comment_panel');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_participant_comment_admin');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_participant_comment_participant');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_participant_comment_selector');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_participant_comment_mentor');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_participant_comment_panel');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_selector_comment_admin');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_selector_comment_participant');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_selector_comment_selector');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_selector_comment_mentor');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_selector_comment_panel');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_mentor_comment_admin');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_mentor_comment_participant');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_mentor_comment_selector');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_mentor_comment_mentor');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_mentor_comment_panel');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_panel_comment_admin');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_panel_comment_participant');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_panel_comment_selector');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_panel_comment_mentor');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('comments_panel_comment_panel');
});
$('#comment-hint').on('click', function(e){
    $("#comment-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#comment-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/feedback_emails.html.erb
<div id="mainnavi">
  <%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>
<div id="mailfunctionAnker"></div>
<div id="sidebar">
  <%= render "admin/organisations/setup_header" %>
</div>
<div id="rightcontent" class="closable_h2 two_sided_right_content">
  <%= form_tag feedback_emails_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/feedback_form" %>
  <% end %>
</div><!-- #rightcontent -->  

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_admin');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_participant');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_selector');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_mentor');
});
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_panel');
});
$('#feedback-hint').on('click', function(e){
  $("#fedback-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#fedback-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/join_team.html.erb
<div id="mainnavi">
	<%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
 	<%= render "admin/organisations/setup_header" %>
</div>

<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag join_team_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/join_team_form" %>
<% end %>
</div>

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_join_team');
});
$('#join-team-hint').on('click', function(e){
    $("#join-team-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#join-team-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/mentor_offer_invite.html.erb
<div id="mainnavi">
	<%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
 	<%= render "admin/organisations/setup_header" %>
</div>

<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag mentor_offer_invite_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/mentor_offer_form" %>
<% end %>
</div>

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_mentor_offer');
});
$('#mentor-offer-hint').on('click', function(e){
    $("#mentor-offer-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#mentor-offer-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/submit_pitch.html.erb
<div id="mainnavi">
	<%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
 	<%= render "admin/organisations/setup_header" %>
</div>

<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag submit_pitch_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/submit_pitch_form" %>
<% end %>
</div>

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_submit_pitch');
});
$('#submit-pitch-hint').on('click', function(e){
    $("#submit-pitch-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#submit-pitch-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/team_member_invite.html.erb
<div id="mainnavi">
	<%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
 	<%= render "admin/organisations/setup_header" %>
</div>
 
<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag team_member_invite_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/team_member_invite" %>
<% end %>
</div>

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_team_member_invite');
});

$('#team-hint').on('click', function(e){
    $("#team-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#team-hintbox{border:2px solid;
border-radius:25px;}
</style>

app/views/admin/organisations/customize_email/team_mentor_invite.html.erb
<div id="mainnavi">
    <%= render "admin/organisations/header" %>
  <!-- Checking if company id not equal 766 (bcs program). Here can be added condition for default(newer) programs. -->
  <div class="clr"></div>
</div>

<div id="mailfunctionAnker"></div>
<div id="sidebar">
    <%= render "admin/organisations/setup_header" %>
</div>
 
<div id="rightcontent" class="closable_h2 two_sided_right_content">
<%= form_tag team_mentor_invite_save_admin_organisations_customize_email_index_path, :method => :post  do %>
    <%= render "messages/team_mentor_invite" %>
<% end %>
</div>

<script>
bkLib.onDomLoaded(function() {
  new nicEditor().panelInstance('feedback_team_mentor_invite');
});

$('#team-hint').on('click', function(e){
    $("#team-hintbox").toggle();
});
$(".hint-title[rel=tooltip]").tooltip();
</script>

<style>
.hint-title{padding:5px;font-weight:bold;}
#team-hintbox{border:2px solid;
border-radius:25px;}
</style>