config/routes.rb
require 'resque/server'
require 'resque_scheduler'
require 'subdomain'
Resque::Scheduler.dynamic = true
Apptual::Application.routes.draw do

  get "programs/:id/search" => "search#index", :as => :index_search

  devise_for :users, :controllers => {:registrations => 
    "registrations", :invitations => 'invitations', :omniauth_callbacks => "users/omniauth_callbacks",
     :passwords => "passwords", :confirmations => 'confirmations'
  } do
      get  "/users/invitation/accept" => "invitations#accept"
      get  "/users/invitation/check_email" => "invitations#check_email"
      get  "/users/invitation/find_user" => "invitations#find_user"
      get  "/users/invitation/invite_existing" => "invitations#invite_existing"
  end
  
  devise_scope :user do
    get "/users/sign_up/step_2/:id" => "registrations#step_2", 
      :as => :step_2_user_registration
    get "/users/force/:id" => "registrations#force_sign_in", :as => :force_sign_in
    put "users/update_without_session/:id" => "registrations#update_without_session",
      :as => :update_without_session_registration
    get "/users/about_me" => "registrations#about_me", :as => :about_me_registration
    put "/users/update_about_me" => "registrations#update_about_me", :as => :update_about_me_registration
    put "/users/accept_invitation" => "registrations#accept_invitation", :as => :invitation_validation
    get "/profile/:id" => "registrations#show", :as => :user

    post 'users/omniauth_callbacks/create_twitter_user' => "users/omniauth_callbacks#create_twitter_user"
    get "/users/finish" => "registrations#finish", :as => :finish_registration
    get "users/show_faq" => "registrations#show_faq"
    get "users/pages_visited" => "registrations#pages_visited"
    put "/users/social_update" => "registrations#social_update", :as => :social_update
    get "/users/edit_user" => "registrations#edit_user", :as => :edit_user
    put "users/admin_update/:id" => "registrations#admin_update", :as => :admin_update
  end
  resources :organisations do
    get "/members/:role_code" => "organisations#members", :on => :member,
      :as => :members
    get   :eco_login,      on: :member
    get   :buzz,      on: :member
    post  :buzz_post, on: :member
    get   :popup_details,      on: :member
    resources :community_feeds, :only => [:destroy] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
    end
    resource :summary, :controller => :eco_summaries
    get :faqs,      on: :member    
    put :faq_save,      on: :member
    put :faq_update,      on: :member
    delete :faq_destroy,      on: :member
    post :contact_us, :on => :member
    resources :coupons, :only => [:index, :show, :create, :new, :destroy]
    resources :subscriptions, :only => [:edit, :create, :new, :update, :delete] do
      get   :soft_deleted_user,   on: :collection
    end
    
    get   :reactivate_account,  on: :collection
    get   :deactivate_account,  on: :collection

    get :badge_authority_details
    post :badge_authority_details_save
    
  end

  resources :comments, :only => [:create, :destroy] do
    put :like, :on => :member
    put :unlike, :on => :member
    get :like_from_mail, :on => :member
  end

  resources :surveys do
    resources :questions
  end

  resources :payments do
    get :plans, on: :collection
    get :subscriptions, on: :collection
    get :check_vat, on: :collection
    get :refund, on: :collection    
  end

  resources :ecosystems, :only => [:index, :show, :create, :new, :destroy]

  resources :user_contact_requests, :only => [:create]

  resources :programs do
    get "manage_form"
    put "manage_form_save"
    put "feed_form"
    get "change_feed_form"
    get :dashboard
    get :export_users_detail
    get :export_projects_detail
    get :download_phase_in_csv, :on => :member
    get :get_action_list
    get :community_tab
    put :update_custom_filter
    get :get_rule
    put :update_rule
    delete :delete_rule
    collection do
      post :contact_us
    end

    resources :voting_sheets, :only => :none do
      post :download,:on=>:collection
    end

    resources :messages, :only => :none do
      put :participants, :on => :collection
      put :pitches, :on => :collection
      put :mentor_pitches, :on => :collection
      put :phase_messages, :on => :collection
      put :msg_pitch_team, :on => :collection
      get :customize_email_messages, :on => :collection
      get :feedback_emails,:on=>:collection
      post :feedback_emails_save,:on=>:collection
      get :admin_invite ,:on=>:collection
      post :admin_invite_save ,:on => :collection
      get :team_member_invite ,:on=>:collection
      post :team_member_invite_save ,:on => :collection
      get :team_mentor_invite ,:on=>:collection
      post :team_mentor_invite_save ,:on => :collection
      get :comment_emails,:on=>:collection
      post :comment_emails_save,:on=>:collection
      get :mentor_offer_invite,:on=>:collection
      post :mentor_offer_invite_save,:on=>:collection
      get :join_team,:on=>:collection
      post :join_team_save,:on=>:collection
      get :submit_pitch,:on=>:collection
      post :submit_pitch_save,:on=>:collection
      get :collaboration_successfull,:on=>:collection
      post :collaboration_successfull_save,:on=>:collection
      get :download_csv,:on=>:collection
      get :join_team_email,:on=>:collection
      post :join_team_email_save,:on=>:collection
      get :declines_join_team_request,:on=>:collection
      post :declines_join_team_request_save,:on=>:collection
      get :rate_events_mail,:on=>:collection
      post :rate_events_mail_save,:on=>:collection
    end

    resources :customisations, :only => [:new, :create] do
      delete :delete_custom_fields, :on => :collection
      put :remove_basic_fields, on: :collection
    end

    resources :faqs, :only => [:new, :create, :show, :update, :destroy]
    resources :settings, :only => [:new, :create] do
      post :cloneable, on: :collection
    end

    resources :workflows, :only => [:index, :create] do
      put :toggle_status, on: :member
      put :achieved, on: :member
      put :undo, on: :member
      delete :delete_milestone, on: :member
    end

    resources :events do
      get :accept, :on => :member
      post :reject_participant, :on => :collection
      get :manage_participant, :on => :member
      get :confirm_participant, :on => :collection
      resources :event_sessions, :only => [:destroy] do
        get :export_event_session, :on => :member
        get :print_event_session, :on => :member
        post :message_all, :on => :collection
      end
    end

    resources :community_feeds, :only => [:index, :create, :destroy, :show] do
      put :like, :on => :member
      put :unlike, :on => :member
      put :feature, :on => :member
      put :unfeature, :on => :member
      put :non_sticky, :on => :member
      put :sticky, :on => :member
      put :remove_from_blog, :on => :member
      put :add_to_blog, :on => :member
      put :remove_from_eco_blog, :on => :member
      put :add_to_eco_blog, :on => :member
      get :like_from_mail, :on => :member
    end
    resource :summary, :controller => :program_summaries do
      get :authorize_eventbrite_account, :on => :member
      get :create_eventbrite_account, :on => :member
      put :add_eventbrite_user_key, :on => :member
      get :fetch_eventbrite_events, :on => :member
      post :create_eventbrite_events, :on => :member
      put :generate_nav_links, :on => :collection
    end
    resource :program_plans do
      get :attending, :on => :member
      get :not_attending, :on => :member
      get :attendees, :on => :member
    end
    resource :scope, :controller => :program_scopes
    resource :invitation, :controller => :program_invitations do
      get :invites, :on => :collection
      post :send_invites, :on => :collection
    end
    
    resource :due_diligence do
      get :judging_score, :on => :collection
      get :export_judging_details, :on => :collection
    end
    
    resources :phases, :only => :index do
      put :task_manager, :on => :collection
      post :task_manager, :on => :collection
      post :remind, :on => :collection
      post :message_all, :on => :collection
      get :manage, :on => :collection
      put :transition, :on => :collection
    end
    resources :pitches do
      post :iteration, :on => :member
      get :feeds, :on => :member
      get :team, :on => :member
      get :nudge, :on => :member
      get :be_mentor, :on => :member
      put :be_member, :on => :member
      get :join_team, :on => :member
      put :join_team, :on => :member
      put :invite_mentor, :on => :member
      get :contacts, :on => :member
      put :add_mentor, :on => :member
      put :remove_mentor, :on => :member
      put :add_membership_requester, :on => :member
      put :remove_membership_requester, :on => :member
      put :add_collaborater_requester, :on => :member
      put :remove_collaborater_requester, :on => :member
      put :shortlist, :on => :member
      put :finalist, :on => :member
      put :skills_needed, :on => :member
      post :due_diligence, :on => :member
      get :recommended_events, :on => :member
      put :assign_mentor, :on => :member
      delete :gallery_pic_remove, :on => :member
      
      resources :edit_pitch_field, :only => :none do
        get :toggle_edit_status, :on => :collection
      end
      
      resources :pitch_privacies, :only => [] do
        get :change_privacy_of_pitch, :on => :collection
      end
      
      resources :pitch_work_flow, :only => [] do
        get :check_required_fields, :on => :collection
      end
      
      get '/courses/:course_id/show' => "courses#show", as: :course_show
      post :refer_pitch_some_one, :on => :member
      post :be_collaborater, :on => :member
      resources :documents, :only => [:index, :create, :destroy] do

app/models/survey.rb
class Survey
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :questions, :dependent => :destroy
  has_one :question_order, :dependent => :destroy
  has_many :answers, :dependent => :destroy

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :question_order, reject_if: :all_blank

  belongs_to :user
  belongs_to :program
  belongs_to :organisation

  mount_uploader :avatar, AvatarUploader

  CATEGORIES = ["One-Off", "Recurring"]
  TARGET_AUDIENCE= ["Projects","Participants","Mentors"]

  field :name,                          type: String
  field :category,                      type: String
  field :recurring_period,              type: Integer
  field :end_date,                      type: Date
  field :description,                   type: String
  field :show_results_to_participants,  type: Boolean, default: false
  field :target_audience,               type: String
  field :total_audience,                type: Array, default: []
  field :audience_started_survey,       type: Array, default: []
  field :audience_completed_survey,     type: Array, default: []
  field :time,                          type: Time
  field :recurring_period_update,       type: Time
  field :visibility,                    type: Array, default: []
  field :content,                       type: String, default: ""
  field :subject,                       type: String, default: ""
  
  before_save :audience

  def create_questions questions
    questions.each do |field|
      if field[:question_text].present?
        option_attributes = field.delete("option_fields")
        option_attributes ||= []
        parent_field = save_field(field)
        destroy_dependent_option_fields parent_field
        option_attributes.each do |option_field|
          save_field option_field, parent_field.id
        end
      end
    end if questions
  end

  def audience
    if target_audience_changed?
      case target_audience
        when "Projects"
          audience = User.in(id: program.pitches.map(&:team).flatten).map(&:id)
        when "Participants"
          audience = User.in("_participant" => program.id.to_s).map(&:id)
        when "Mentors"
          audience = User.in("_mentor" => program.id.to_s).map(&:id)
      end
      self[:total_audience] = audience
    end
  end

  def audience_not_completed
    total_audience-audience_completed_survey
  end
  
  def visible? place
    visibility.include? place
  end

  private
  
  def save_field field, parent_field_id = ""
    if field[:id].present?
      cf = questions.find(field[:id])
      cf.update_attributes(field.merge({parent_id: parent_field_id}))
    else
      cf = questions.new(field.merge({parent_id: parent_field_id}))
      cf.save
    end
    return cf
  end

  def destroy_dependent_option_fields parent_field
    questions.where(parent_id: parent_field.id.to_s).delete
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController


  def new
    @program= context_program
    @surveys= context_program.surveys.all
    @survey = context_program.surveys.build(organisation: current_organisation)
    @survey.build_question_order
  end

  def create
    survey = context_program.surveys.build(params[:survey])
    survey.organisation, survey.user= current_organisation, current_user
    if survey.save
      flash[:notice] = "Survey Successfully created"
      redirect_to new_survey_question_path(survey)
    else
      render :action => :new
    end
  end
  
  def edit
    @program=context_program
    @survey= context_program.surveys.find(params[:id])
    @questions=@survey.questions
    @survey.build_question_order unless @survey.question_order.present?
  end

  def update
    @survey = context_program.surveys.find(params[:id])
    @survey.update_attributes(params[:survey])
    @survey.create_questions params[:question]
    question_order = QuestionOrder.find_or_initialize_by(survey_id: @survey.id)
    question_order.update_attributes(:order => params[:order])
    flash[:notice] = "Updated Successfully"
    redirect_to :back
  end

  def destroy
    @survey = context_program.surveys.find(params[:id])
    @survey.destroy
    ActivityFeed.where(survey_id: params[:id]).delete_all
    redirect_to :back
  end

  def answers
    @survey = Survey.where(:id => params[:id]).first
    @program = @survey.program
    @survey.audience_started_survey << current_user.id unless (params[:redirected] or @survey.audience_started_survey.include? current_user.id)
    @survey.save
    render layout: "application_new_design"
  end
  
  def update_answers
    @survey = Survey.where(:id => params[:id]).first
    if params[:submit]
      @survey.audience_completed_survey << current_user.id unless @survey.audience_completed_survey.include? current_user.id
      @survey.audience_started_survey.delete(current_user.id)
      @survey.save
    end
    params[:survey][:custom_fields].each do|question_id, answer|
      ans = @survey.answers.find_or_initialize_by(question_id: question_id)
      ans.update_attributes(:answer_text=> answer, :user_id => current_user.id)
    end if params[:survey]
    redirect_to answers_program_survey_path(@survey.program, @survey, redirected: true)
  end

  def message_users
    survey = Survey.where(:id => params[:id]).first
    case params[:audience]
      when "completed"
        user_ids = survey.audience_completed_survey.uniq
      when "started"
        user_ids = survey.audience_started_survey.uniq
      when "not_completed"
        user_ids = survey.audience_not_completed
    end
    users = User.in(id: user_ids)
    requester = current_user.id
    Resque.enqueue(App::Background::SurveyMessageMail, params[:id], user_ids, requester, params[:subject], params[:message])
    redirect_to :back
  end
end

app/views/surveys/_form.html.erb
<%= form_for survey do |f| %>
  <%- if survey.errors.any? %>
    <ul>
      <%- survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= content_tag :div, class: "block" do%>
    <a href="sec1" name="sec1" class="section_nav"></a>
    <h1>My Surveys</h1>
    <%= content_tag :table, class: "settings full_width_table" do%>
      <%= content_tag :tbody do%>
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label "Survey Title" %>
          <% end %>
     
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label "Type" %>
          <% end %>
        
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label "Options" %>
          <% end %>
        <% end %>
        <% @surveys.each do |survey|%>
          <%= content_tag :tr do%>
            <%= content_tag :td, class: "lbl" do%>
              <%= survey.name%>
            <% end %>
            <%= content_tag :td, class: "lbl" do%>
              <%= survey.category%>
            <% end %>
            <%= content_tag :td, class: "lbl" do%>
              <%= link_to "Edit",edit_program_survey_path(context_program,survey)%>
              <%= "/"%>
              <%= link_to "Delete",program_survey_path(context_program,survey), method: :delete, action: :destroy, data: { confirm: 'This will Delete all the data associated with this Survey.' }%>

            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  
  <%= content_tag :div, class: "block" do%>
    <a href="sec2" name="sec2" class="section_nav"></a>
    <h1><%= survey.new_record? ? "New Survey" : "Edit Survey" %></h1>
    <%= content_tag :table, class: "settings full_width_table" do%>
      <%= content_tag :tbody do%>
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label :name , "Survey Title",class: "mend_field_label" %>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= f.text_field :name, :required => true, :placeholder => "Title", class: "form-control" %>
          <% end %>
        <% end %>

        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label :avatar, "Survey Graphic",class: "mend_field_label"%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
          	<div class="browse-wrapper">
            <%= f.file_field :avatar,:required => true, :class => "form-control"%>
            </div>
          <% end %>
        <% end %>
        
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label :category, "Survey Type" %>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= f.select :category, Survey::CATEGORIES,{}, class: "form-control", :required => true %>
          <% end %>
        <% end %>
        
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label :target_audience, "Target",class: "mend_field_label"%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= f.select :target_audience,Survey::TARGET_AUDIENCE,{:prompt => "--Choose Target--"},:required => true,:class => "form-control"%>
         <% end %>

          <%#= content_tag :td, class: "lbl" do%>
            <%#= f.label :end_date%>
          <%# end %>
          <%#= content_tag :td, class: "col_setting" do %>
            <%#= f.text_field :end_date, :class => "datepicker_std program_plan_td1 form-control" %>
          <%# end %>
        <% end%>
        
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= f.label :description%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= f.text_area :description, :class => "form-control" %>
          <% end %>
        <% end %>
    <% end %>
  <%end%>
    <%= f.submit "Save", id: "submit"%>
    <%= f.submit "Cancel", :type => "reset",id: "submit", :style => "background:#07b291;" %>
    <%= tag 'br'%>
  <% end %>
<% end %>

app/views/surveys/edit.html.erb
<%= form_for @survey, :program_id => @program.id do |surveys| %>
  <% page = "setup_program"; ppage = "surveys"%>
  <%= render "shared/bs_navbar", :page => page, :ppage => ppage %>
<div class="row page_head">
  <div class="col-md-8">
    <h3>
      <i class="gn-icon gn-icon-stack-idea gn-icon-large"></i>
      Edit Survey
      <i class="glyphicon glyphicon-question-sign help-sign" data-toggle="tooltip" data-placement="bottom" title="Edit survey allows you to edit a previously created survey"></i>
    </h3>
  </div>
  <div class="col-md-4 breadcrumb">
    <a href="#"><%=context_program.title%></a> / <a href=<%= context_program.try(:persisted?) ? edit_program_url(context_program) : new_program_url %>>Setup</a> / <a href="#" class="active_bread">Create Survey</a>
  </div>
</div>
<div class="row main-row">
	<div class="col-md-10 main-right-section">
		<h2 class="titleLine title-normal"><span>Main section</span></h2>
  <div class="block">
	<a href="sec1" name="sec1" class="section_nav"></a>
	<h1>Survey: <%=@survey.name%> </h1>
	</div>	
    <%= content_tag :table, class: "settings full_width_table" do%>
      <%= content_tag :tbody do%>
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= surveys.label :name, "Survey Title",class: "mend_field_label"%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= surveys.text_field :name, :required => true, class: "form-control" %>
          <% end %>
        <% end %>
        
          <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= surveys.label :avatar, "Survey Graphic",class: "mend_field_label "%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <% required = @survey.avatar.present? ? false :"required" %>
            <%= surveys.file_field :avatar, class: "form-control",required: required %>
          <% end %>
            <% if @survey.avatar.present? %>
              <% file = @survey.avatar_url.split(".")[-1] %>
                <% if ["jpeg","jpg","png","gif"].include?(file.downcase) %>
                  <%= image_tag @survey.avatar , :style => "width:170px;height:160px"%>
                <% else %>
                  <%= link_to("#{root_url}#{@survey.avatar}", "#{root_url}#{@survey.avatar_url}", :target =>"_blank", :class => 'text_underline') %>
                <% end %>
            <% end %>
        <% end %>
        
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= surveys.label :category,"Survey Type" %>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= surveys.select :category, Survey::CATEGORIES,{}, class: "form-control", :required => true %>
          <% end %>
        <% end %>
      <% end %>
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= surveys.label :target_audience, "Target", class: "mend_field_label"%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= surveys.select :target_audience,Survey::TARGET_AUDIENCE ,{:prompt => "--Choose Target--"},:required => true,:class => "form-control"%>
          <% end %>
          <%#= content_tag :td, class: "lbl" do%>
            <%#= surveys.label :end_date%>
          <%# end%>
          <%#= content_tag :td, class: "col_setting" do %>
            <%#= surveys.text_field :end_date, :class => "datepicker_std program_plan_td1 form-control" %>
          <%# end%>
         <% end %>
        
        <%= content_tag :tr do%>
          <%= content_tag :td, class: "lbl" do%>
            <%= surveys.label :description%>
          <% end %>
          <%= content_tag :td, class: "col_setting" do %>
            <%= surveys.text_area :description, :class => "form-control" %>
          <% end %>
      <% end %>
    <% end %>

     <%= render "surveys/edit_survey_questions", f:surveys, survey:@survey, question:@survey.questions.build(user: current_user) %>
      <%= surveys.submit "Save", id: "submit" %>
    <%= tag 'br'%>
  <% end %>
  </div>
	<div class="col-md-2 stick_me">
		<ul class="navigator-menu">
			<li id="nav_sec1" class="active-navigator-title">
				<p>Main Section</p>
				<ul>
					<li><a href="#sec1">Survey: <%= @survey.name%></a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<div style="display: none">
   <div class="lightbox_box" id="help_content_ques">
   </div>
</div>

<%= javascript_include_tag "jquery.sticky-kit.min" %>
<style>
.input-size1 {
    width: 196px;
}
.column .portlet .portlet-header{
  cursor:pointer;
}
.column {
width: 100%;
overflow-y: hidden;
}

.portlet {
margin-bottom:1em;
border:0px;
} 
.portlet-header h2.titleLine {
padding-top:6px;
padding-bottom:6px;
border-bottom: 0px;
line-height: 0px;
margin-bottom: 0px;
margin-top: 0px;
}
.portlet-header {
padding-right: 26px;
padding-left: 12px;
border:0px;
box-shadow: 1px 1px 5px #CCCCCC;
-moz-box-shadow: 1px 1px 5px #CCCCCC;
-webkit-box-shadow: 1px 1px 5px #CCCCCC;
border-radius:0;1px 1px 5px #CCCCCC;
position: relative;
}
.portlet-toggle {
position: absolute;
top: 50%;
right: 0;
margin-top: -8px;
}
.portlet-placeholder {
border: 1px dotted black;
margin: 0 1em 1em 0;
height: 42px;
}
label.section-title{ font-size:18px;}
a.doc_upload:hover{
  text-decoration: underline;
  color:#017FB2
}

a.doc_upload{
  color:#2B542C; 
}
.panel-title a:first-child{
  float: left;
  }
</style>
<% if @survey.question_order.try(:order).present? %>
   <% order = @survey.question_order.order.gsub("-",",").split(",") %>
   <% question_arrange_order = Hash[*order].values %>
   <% question_arrange_order = (raw question_arrange_order) %>
<% end %>
<script type="text/javascript" charset="utf-8">
 $(function() {
<% if @survey.question_order.try(:order).present? %>
    var arrValuesForOrder = <%= question_arrange_order %>;
    var div = $("div.column"),
        items = $("div.column div.portlet");

    for (var i = arrValuesForOrder.length - 1; i >= 0; i--) {
        // arrValuesForOrder[i] element to move
        // i = index to move element at
        div.prepend(items.get(arrValuesForOrder[i] - 1));
    }
    var i = 1;
    $('.column').find('.panel-title').each(function() {
      $(this).html("Question " + i);
      i++;
    });
  <% end %>
  $('div.column').sortable({
    stop: function(event, div) {
      var order_list = $("div.column").sortable('toArray');
        $("#survey_question_order").val(order_list)
      var i = 1;
      $('.column').find('.panel-title').each(function() {
        $(this).html("Question " + i);
        i++;
      });
    },
  });
  $( ".column" ).sortable({
    connectWith: ".column",
    handle: ".portlet-header",
    cancel: ".portlet-toggle",
    placeholder: "portlet-placeholder ui-corner-all"
  });
  $( ".portlet" )
  .addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
  .find( ".portlet-header" )
  .addClass( "ui-widget-header ui-corner-all" )
  .prepend( "<span class='ui-icon ui-icon-minusthick portlet-toggle'></span>");
  $( ".portlet-toggle" ).click(function() {
    var icon = $( this );
    icon.toggleClass( "ui-icon-minusthick ui-icon-plusthick" );
    icon.closest( ".portlet" ).find( ".portlet-content" ).toggle();
    });
  }); 
  
   $(document).on('click', ".add_custom_help", function(e){
   current_obj = $(this);
   url = $(this).data('url');
   $.ajax({
     url: url,
     type: 'get',
     dataType: 'html',
     contentType: 'application/json; charser=utf-8',
     success: function(data){
      $("#help_content_ques").html(data);
     },
     error: function(){
      alert('Request failed. Sorry, we are analyzing the cause of this problem');
     }
   })
 });
  jQuery(document).ready(function($){
    $(".stick_me").stick_in_parent({
      parent: $(".two_sides_content"),
      offset_top: 300
    });
    
    $('.help-sign').tooltip();
  });
  $('.navigator-menu li ul li a').click(function(){
      $('.navigator-menu li ul li').removeClass('active-navigator-section');
      $('.navigator-menu li').removeClass('active-navigator-title');
      $(this).parent().addClass('active-navigator-section');
      $(this).parent().parent().parent().addClass('active-navigator-title');
    $('html, body').animate({
        scrollTop: $('[name="' + $.attr(this, 'href').substr(1) + '"]').offset().top - 60
    }, 500);
    return false;
  });
  $("[rel=tooltip]").tooltip();
</script>